name: GitHub TruffleHog Action Test Reusable Workflow
run-name: ${{ github.actor }} running local workflow

on:
    push:
      branches:
        - '**'
    pull_request:
      branches:
        - '**'
      types:
        - opened
        - reopened

jobs:
    # call-workflow-in-local-repo:
    #   uses: octo-org/this-repo/.github/workflows/workflow.yaml@172239021f7ba04fe7327647b213799853a9eb89
    call-workflow-in-local-repo:
      uses: ./.github/workflows/workflow.yaml
      permissions:
        contents: read
        id-token: write
        issues: write
        pull-requests: write
    # call-workflow-in-another-repo:
    #   uses: octo-org/another-repo/.github/workflows/workflow.yaml@v1
