name: GitHub TruffleHog Action Test Reusable Workflow
run-name: ${{ github.actor }} running local workflow

on:
    push:
      branches:
        - '**'
    pull_request:
      branches:
        - '**'
      types:
        - opened
        - reopened

jobs:
    call-workflow-in-local-repo:
      uses: ./.github/workflows/workflow.yaml
      permissions:
        contents: read
        id-token: write
        issues: write
        pull-requests: write
