name: GitHub TruffleHog Action Test Reusable Remote Workflow
run-name: ${{ github.actor }} running remote workflow

on:
    push:
      branches:
        - '**'
    pull_request:
      branches:
        - '**'
      types:
        - opened
        - reopened

jobs:
    secrets-scanning:
      uses: pbs/gha-public-workflows/.github/workflows/secrets-scanning.yml@main
      permissions:
        contents: read
        id-token: write
        issues: write
        pull-requests: write
